owner: negru 
repo: upptime 

sites:
  - name: ns1
    url: http://208.68.19.203
    icon: https://raw.githubusercontent.com/negru/upptime/master/assets/favicon.ico
    check: "tcp-ping"
    port: 80
    maxResponseTime: 3000
    
  - name: MD1
    url: http://208.68.19.200  
    icon: https://raw.githubusercontent.com/negru/upptime/master/assets/favicon.ico
    check: "tcp-ping"
    port: 80
    maxResponseTime: 3000
    
  - name: MD2
    url: http://208.68.19.206   
    icon: https://raw.githubusercontent.com/negru/upptime/master/assets/favicon.ico
    check: "tcp-ping"
    port: 80
    maxResponseTime: 3000
    
  - name: MD3
    url: http://208.68.19.201 
    icon: https://raw.githubusercontent.com/negru/upptime/master/assets/favicon.ico
    check: "tcp-ping"
    port: 80
    maxResponseTime: 3000
    
  - name: MT1
    url: http://mt1.hostdent.com/   
    icon: https://raw.githubusercontent.com/negru/upptime/master/assets/favicon-mt.ico
    check: "tcp-ping"
    port: 80
    maxResponseTime: 3000
    
  - name: NS2
    url: https://ns2.hostdent.com
    icon: https://raw.githubusercontent.com/negru/upptime/master/assets/favicon.ico
    check: "tcp-ping"
    port: 80
    maxResponseTime: 3000
    
  - name: NS4
    url: http://208.68.19.204
    icon: https://raw.githubusercontent.com/negru/upptime/master/assets/favicon.ico
    check: "tcp-ping"
    port: 80
    maxResponseTime: 3000
    
  - name: NS7
    url: http://68.148.200.253
    icon: https://raw.githubusercontent.com/negru/upptime/master/assets/favicon.ico
    check: "tcp-ping"
    port: 80
    maxResponseTime: 3000    
    #expectedStatusCodes:
    #  - 401
    #__dangerous__insecure: true    
                
status-website:
  robotsText: "User-agent: * \n Disallow: /"
  metaTags:
    - name: "color-scheme"
      content: "light"
    - name: "robots"
      content: "noindex"
  cname: status.hostdent.com
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/negru/upptime/master/assets/md.svg
  favicon: https://raw.githubusercontent.com/negru/upptime/master/assets/favicon.ico
  name: HD & MD Status
  introTitle: "**Status**"
  introMessage: HD & MD
  navbar:
    - title: Top
      href: /
      
i18n:
  footer: © 2022 HD & MD


# https://upptime.js.org/docs/configuration
