owner: negru 
repo: upptime 

sites:
  - name: MD1
    url: http://md1.hostdent.com
  - name: MD2
    url: https://md2.hostdent.com
  - name: MD3
    url: https://md3.hostdent.com
  - name: NS2
    url: https://ns2.hostdent.com
  - name: NS4
    url: https://ns4.hostdent.com
    
status-website:
  # cname: status.hostdent.com
  baseUrl: /upptime
  logoUrl: https://marketdental.com/public/images/favicons/safari-pinned-tab.svg
  name: HD & MD Status
  introTitle: "**HD Status**"
  introMessage: HD & MD
  navbar:
    - title: Status
      href: /
      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
